"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 09:13:54.799893
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('contract_kw', sa.Float(), nullable=False),
    sa.Column('limit_ratio', sa.Float(), server_default='0.9', nullable=False),
    sa.PrimaryKeyConstraint('station_id', name=op.f('pk_station'))
    )
    op.create_table('vehicle_spec',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('battery_kwh', sa.Float(), nullable=False),
    sa.Column('max_dc_kw', sa.Float(), nullable=False),
    sa.Column('max_ac_kw', sa.Float(), nullable=False),
    sa.Column('taper_start_soc', sa.Float(), server_default='80', nullable=False),
    sa.Column('taper_min_ratio', sa.Float(), server_default='0.2', nullable=False),
    sa.Column('efficiency', sa.Float(), server_default='0.92', nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id', name=op.f('pk_vehicle_spec')),
    sa.UniqueConstraint('model_name', name=op.f('uq_vehicle_spec_model_name'))
    )
    op.create_table('charger',
    sa.Column('charger_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('rated_kw', sa.Float(), nullable=False),
    sa.Column('connector_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='idle', nullable=False),
    sa.CheckConstraint("status IN ('idle','charging','fault')", name=op.f('ck_charger_status_valid')),
    sa.CheckConstraint('rated_kw > 0', name=op.f('ck_charger_rated_kw_positive')),
    sa.ForeignKeyConstraint(['station_id'], ['station.station_id'], name=op.f('fk_charger_station_id_station')),
    sa.PrimaryKeyConstraint('charger_id', name=op.f('pk_charger'))
    )
    with op.batch_alter_table('charger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charger_station_id'), ['station_id'], unique=False)

    op.create_table('kpi_daily',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('avg_wait_min', sa.Float(), nullable=False),
    sa.Column('load_factor', sa.Float(), nullable=False),
    sa.Column('peak_reduction_kw', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.station_id'], name=op.f('fk_kpi_daily_station_id_station')),
    sa.PrimaryKeyConstraint('station_id', 'date', name=op.f('pk_kpi_daily'))
    )
    op.create_table('load_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_kw', sa.Float(), nullable=False),
    sa.Column('contract_kw', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.CheckConstraint("mode IN ('baseline','controlled')", name=op.f('ck_load_log_mode_valid')),
    sa.ForeignKeyConstraint(['station_id'], ['station.station_id'], name=op.f('fk_load_log_station_id_station')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_load_log'))
    )
    with op.batch_alter_table('load_log', schema=None) as batch_op:
        batch_op.create_index('ix_load_log_station_mode_ts', ['station_id', 'mode', 'ts'], unique=False)

    op.create_table('charge_session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('charger_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('anon_user_id', sa.String(length=64), nullable=False),
    sa.Column('soc_start', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('soc_target', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('soc_current', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('queue_pos', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alloc_kw', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('calc_minutes', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('calc_detail', sa.JSON(), nullable=True),
    sa.CheckConstraint("status IN ('waiting','called','charging','done','cancelled','no_show')", name=op.f('ck_charge_session_status_valid')),
    sa.CheckConstraint('soc_current IS NULL OR soc_current BETWEEN 0 AND 100', name=op.f('ck_charge_session_soc_current_range')),
    sa.CheckConstraint('soc_start < soc_target', name=op.f('ck_charge_session_soc_start_lt_target')),
    sa.CheckConstraint('soc_start BETWEEN 0 AND 100', name=op.f('ck_charge_session_soc_start_range')),
    sa.CheckConstraint('soc_target BETWEEN 0 AND 100', name=op.f('ck_charge_session_soc_target_range')),
    sa.ForeignKeyConstraint(['charger_id'], ['charger.charger_id'], name=op.f('fk_charge_session_charger_id_charger')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_spec.vehicle_id'], name=op.f('fk_charge_session_vehicle_id_vehicle_spec')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_charge_session'))
    )
    with op.batch_alter_table('charge_session', schema=None) as batch_op:
        batch_op.create_index('ix_charge_session_charger_status_queue', ['charger_id', 'status', 'queue_pos'], unique=False)

    op.create_table('session_event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['charge_session.session_id'], name=op.f('fk_session_event_session_id_charge_session')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_session_event'))
    )
    with op.batch_alter_table('session_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_event_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_event_session_id'))

    op.drop_table('session_event')
    with op.batch_alter_table('charge_session', schema=None) as batch_op:
        batch_op.drop_index('ix_charge_session_charger_status_queue')

    op.drop_table('charge_session')
    with op.batch_alter_table('load_log', schema=None) as batch_op:
        batch_op.drop_index('ix_load_log_station_mode_ts')

    op.drop_table('load_log')
    op.drop_table('kpi_daily')
    with op.batch_alter_table('charger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charger_station_id'))

    op.drop_table('charger')
    op.drop_table('vehicle_spec')
    op.drop_table('station')
    # ### end Alembic commands ###
